source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'PodExample-iOS' do
    pod 'SwifterSwift', :path => '../../' # The correct group paths of SwifterSwift in Development Pods.
#    pod 'SwifterSwift', '4.6.0' # The group paths of SwifterSwifte in Pods before version 4.6.0 is incorrect. The source files are not contained in their own subspec groups.
#    pod 'SwifterSwift', :git => 'https://github.com/dklinzh/SwifterSwift.git', :branch => 'pod_install' # The correct group paths of SwifterSwift in Pods as same as that in Development Pods. 

end
