coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project: true
    patch: true
    changes: true

  ignore:
    - "Sources/Extensions/Deprecated/*"
    - "Sources/Extensions/*/Deprecated/*"
    - "Tests/**/*"
