# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwifterSwiftExample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwifterSwiftExample
  pod 'SwifterSwift' , :git => 'https://github.com/omaralbeik/SwifterSwift.git'

end
