name: SwifterSwift

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  Swiftlint:
    runs-on: macos-15
    name: SwiftLint
    steps: 
      - uses: actions/checkout@v1
      - name: SwiftLint
        run: |
          brew update-reset
          brew bundle --no-upgrade
          swiftlint

  CocoaPods:
    name: CocoaPods
    runs-on: macos-15
    strategy:
      matrix:
        platform: ['ios', 'macos', 'tvos', 'watchos']
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.0.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: CocoaPods ${{ matrix.platform }}
      run: bundle exec pod lib lint --skip-tests --allow-warnings --verbose --platforms=${{ matrix.platform }} 

  SwiftPM:
    name: SwiftPM
    runs-on: macos-15
    strategy:
      matrix:
        platform: ['ios', 'macos', 'tvos', 'watchos']
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.0.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
    - name: SwiftPM ${{ matrix.platform }}
      run: |
        set -euo pipefail
        case "${{ matrix.platform }}" in
          ios)
            xcodebuild clean test -workspace . -scheme SwifterSwift-Package -destination "platform=iOS Simulator,name=iPhone 16,OS=26.2"
            ;;
          tvos)
            xcodebuild clean test -workspace . -scheme SwifterSwift-Package -destination "platform=tvOS Simulator,name=Apple TV"
            ;;
          macos)
            xcodebuild clean test -workspace . -scheme SwifterSwift-Package -destination "platform=OS X"
            ;;
          watchos)
            xcodebuild clean test -workspace . -scheme SwifterSwift-Package -destination "platform=watchOS Simulator,name=Apple Watch Series 10 (42mm)"
            ;;
        esac
      
  Linux:
    runs-on: ubuntu-24.04
    container: swift:6.0.1
    steps:
      - uses: actions/checkout@v1
      - name: Linux
        run: swift test --parallel

  Android:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Android Tests
        uses: skiptools/swift-android-action@v2

  WASM:
    runs-on: ubuntu-24.04
    container: swift:6.1
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift SDK for WebAssembly
        run: swift sdk install "https://github.com/swiftwasm/swift/releases/download/swift-wasm-6.1-RELEASE/swift-wasm-6.1-RELEASE-wasm32-unknown-wasi.artifactbundle.zip" --checksum "7550b4c77a55f4b637c376f5d192f297fe185607003a6212ad608276928db992"
      - name: Build for WASM
        run: swift build --swift-sdk wasm32-unknown-wasi
